# Setup
name:         Morphemes
tagline:      Common English morphemes, organized for automated access
baseurl:      ""
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
