# Setup
name:         Morphemes
tagline:      Common English morphemes, organized for automated access
baseurl:      "https://github.com/colingoldberg/morphemes/blob/master/docs"
locale:       "en"

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
